/**
 * Types for static image imports.
 *
 * Next declares `*.webp` and friends in `next/image-types/global`, which is
 * normally reached via `next-env.d.ts`. But `next-env.d.ts` is GENERATED by
 * `next dev` / `next build` and is gitignored, so on a clean checkout it does
 * not exist — and the CI Typecheck job runs `tsc --noEmit` without building
 * first. The result was five `TS2307: Cannot find module '...webp'` errors that
 * could not be reproduced on any machine that had ever run a build, which is
 * every developer machine.
 *
 * Referencing the types from a committed file makes the typecheck independent
 * of build order and of whatever happens to be lying around in the working
 * tree. Found by CI on the first PR that imported an image — the gate earning
 * its keep on a class of bug that only appears on a clean clone.
 */

/// <reference types="next/image-types/global" />
